### PR TITLE
Add Kubebuilder methods for conversion webhooks

### PR DESCRIPTION
**Pull request by nicholasjackson**
This PR adds Kubebuilder methods that allow the SMI SDK objects to be used with Kubebuilder conversion webhooks.

Just raising this for exposure.

### CODE REVIEW

**Comment by michelleN** [comment]
@nicholasjackson - please let us know when this is ready for a review!

**Review by michelleN — COMMENTED** [review]
@nicholasjackson - please let us know when this is ready for a review!

**Comment by michelleN** [comment]
Talked to @nicholasjackson offline and he said this is ready for review. Took off the DO NOT MERGE text and wip label. Thanks @nicholasjackson !

**Comment by leecalcote** [comment]
Excellent. 🙂

**Comment by nicholasjackson** [comment]
Hi @michelleN I have resolved all the comments, I actually found a couple of other things where the convert logic was not setting the API version correctly. Fixed these too.

**Review by michelleN — APPROVED** [review]
Thank you @nicholasjackson !

**Pull request merged**
